spring.application.name=rocket-vpn
spring.datasource.url=jdbc:h2:file:./data/vpn
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sudo
spring.datasource.password=aptupdate123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

wg.config.path=/etc/wireguard/wg0.conf
wg.interface=wg0
# Network Configuration
wg.interface.address=10.66.66.1/24
wg.client.subnet.prefix=10.66.66
wg.client.dns=8.8.8.8
wg.port=51820
# Leave empty to auto-detect public IP
wg.endpoint.host=rocket.p2dpt.tech

server.port=8080
